package com.model;

// Generated 20 juil. 2018 16:15:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "ARTICLE")
public class Article implements java.io.Serializable {

	private String codArtArt;
	private String libArtArt;
	private int prixUnitArt;
	private int qteDispArt;
	private Set<DetailCmd> detailCmds = new HashSet<DetailCmd>(0);

	public Article() {
	}

	public Article(String codArtArt) {
		this.codArtArt = codArtArt;
	}

	public Article(String codArtArt, String libArtArt, int prixUnitArt,
			int qteDispArt, Set<DetailCmd> detailCmds) {
		this.codArtArt = codArtArt;
		this.libArtArt = libArtArt;
		this.prixUnitArt = prixUnitArt;
		this.qteDispArt = qteDispArt;
		this.detailCmds = detailCmds;
	}

	@Id
	@Column(name = "COD_ART_ART", unique = true, nullable = false, length = 30)
	public String getCodArtArt() {
		return this.codArtArt;
	}

	public void setCodArtArt(String codArtArt) {
		this.codArtArt = codArtArt;
	}

	@Column(name = "LIB_ART_ART", length = 30)
	public String getLibArtArt() {
		return this.libArtArt;
	}

	public void setLibArtArt(String libArtArt) {
		this.libArtArt = libArtArt;
	}

	@Column(name = "PRIX_UNIT_ART", precision = 22, scale = 0)
	public int getPrixUnitArt() {
		return this.prixUnitArt;
	}

	public void setPrixUnitArt(int prixUnitArt) {
		this.prixUnitArt = prixUnitArt;
	}

	@Column(name = "QTE_DISP_ART", precision = 22, scale = 0)
	public int getQteDispArt() {
		return this.qteDispArt;
	}

	public void setQteDispArt(int qteDispArt) {
		this.qteDispArt = qteDispArt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "article")
	public Set<DetailCmd> getDetailCmds() {
		return this.detailCmds;
	}

	public void setDetailCmds(Set<DetailCmd> detailCmds) {
		this.detailCmds = detailCmds;
	}

}
