package com.model;

// Generated 20 juil. 2018 16:15:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "CONTACT")
public class Contact implements java.io.Serializable {

	private String numMatCnt;
	private String nomNomCnt;
	private String nomPrnCnt;
	private String numGsmCnt;
	private String adrEmailCnt;

	public Contact() {
	}

	public Contact(String numMatCnt) {
		this.numMatCnt = numMatCnt;
	}

	public Contact(String numMatCnt, String nomNomCnt, String nomPrnCnt,
			String numGsmCnt, String adrEmailCnt) {
		this.numMatCnt = numMatCnt;
		this.nomNomCnt = nomNomCnt;
		this.nomPrnCnt = nomPrnCnt;
		this.numGsmCnt = numGsmCnt;
		this.adrEmailCnt = adrEmailCnt;
	}

	@Id
	@Column(name = "NUM_MAT_CNT", unique = true, nullable = false, length = 30)
	public String getNumMatCnt() {
		return this.numMatCnt;
	}

	public void setNumMatCnt(String numMatCnt) {
		this.numMatCnt = numMatCnt;
	}

	@Column(name = "NOM_NOM_CNT", length = 30)
	public String getNomNomCnt() {
		return this.nomNomCnt;
	}

	public void setNomNomCnt(String nomNomCnt) {
		this.nomNomCnt = nomNomCnt;
	}

	@Column(name = "NOM_PRN_CNT", length = 30)
	public String getNomPrnCnt() {
		return this.nomPrnCnt;
	}

	public void setNomPrnCnt(String nomPrnCnt) {
		this.nomPrnCnt = nomPrnCnt;
	}

	@Column(name = "NUM_GSM_CNT", length = 30)
	public String getNumGsmCnt() {
		return this.numGsmCnt;
	}

	public void setNumGsmCnt(String numGsmCnt) {
		this.numGsmCnt = numGsmCnt;
	}

	@Column(name = "ADR_EMAIL_CNT", length = 30)
	public String getAdrEmailCnt() {
		return this.adrEmailCnt;
	}

	public void setAdrEmailCnt(String adrEmailCnt) {
		this.adrEmailCnt = adrEmailCnt;
	}

}
