package com.model;

// Generated 20 juil. 2018 16:15:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetailCmd generated by hbm2java
 */
@Entity
@Table(name = "DETAIL_CMD")
public class DetailCmd implements java.io.Serializable {

	private DetailCmdId id;
	private Article article;
	private Cmd cmd;
	private int qteDispArt;
	private int qteCmdArt;
	private int prixTotalArt;

	public DetailCmd() {
	}

	public DetailCmd(DetailCmdId id, Article article, Cmd cmd) {
		this.id = id;
		this.article = article;
		this.cmd = cmd;
	}

	public DetailCmd(DetailCmdId id, Article article, Cmd cmd,
			int qteDispArt, int qteCmdArt, int prixTotalArt) {
		this.id = id;
		this.article = article;
		this.cmd = cmd;
		this.qteDispArt = qteDispArt;
		this.qteCmdArt = qteCmdArt;
		this.prixTotalArt = prixTotalArt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCmdCmd", column = @Column(name = "ID_CMD_CMD", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "codArtArt", column = @Column(name = "COD_ART_ART", nullable = false, length = 30)) })
	public DetailCmdId getId() {
		return this.id;
	}

	public void setId(DetailCmdId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ART_ART", nullable = false, insertable = false, updatable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CMD_CMD", nullable = false, insertable = false, updatable = false)
	public Cmd getCmd() {
		return this.cmd;
	}

	public void setCmd(Cmd cmd) {
		this.cmd = cmd;
	}

	@Column(name = "QTE_DISP_ART", precision = 22, scale = 0)
	public int getQteDispArt() {
		return this.qteDispArt;
	}

	public void setQteDispArt(int qteDispArt) {
		this.qteDispArt = qteDispArt;
	}

	@Column(name = "QTE_CMD_ART", precision = 22, scale = 0)
	public int getQteCmdArt() {
		return this.qteCmdArt;
	}

	public void setQteCmdArt(int qteCmdArt) {
		this.qteCmdArt = qteCmdArt;
	}

	@Column(name = "PRIX_TOTAL_ART", precision = 22, scale = 0)
	public int getPrixTotalArt() {
		return this.prixTotalArt;
	}

	public void setPrixTotalArt(int prixTotalArt) {
		this.prixTotalArt = prixTotalArt;
	}

}
