package com.model;

// Generated 20 juil. 2018 16:15:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * DetailCmdId generated by hbm2java
 */
@Embeddable
public class DetailCmdId implements java.io.Serializable {

	private Cmd cmd;
	private String codArtArt;

	public DetailCmdId() {
	}

	public DetailCmdId(Cmd cmd, String codArtArt) {
		this.cmd = cmd;
		this.codArtArt = codArtArt;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CMD_CMD")
	public Cmd getCmd() {
		return this.cmd;
	}

	public void setCmd(Cmd cmd) {
		this.cmd = cmd;
	}

	@Column(name = "COD_ART_ART", nullable = false, length = 20)
	public String getCodArtArt() {
		return this.codArtArt;
	}

	public void setCodArtArt(String codArtArt) {
		this.codArtArt = codArtArt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cmd == null) ? 0 : cmd.hashCode());
		result = prime * result + ((codArtArt == null) ? 0 : codArtArt.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DetailCmdId other = (DetailCmdId) obj;
		if (cmd == null) {
			if (other.cmd != null)
				return false;
		} else if (!cmd.equals(other.cmd))
			return false;
		if (codArtArt != other.codArtArt)
			return false;
		return true;
	}
	
	


}
