package com.model;
// Generated Apr 13, 2019 4:52:58 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name = "PERSONNE")
public class Personne implements java.io.Serializable {

	private String matricule;
	private String nom;
	private String prenom;

	public Personne() {
	}

	public Personne(String matricule) {
		this.matricule = matricule;
	}

	public Personne(String matricule, String nom, String prenom) {
		this.matricule = matricule;
		this.nom = nom;
		this.prenom = prenom;
	}

	@Id

	@Column(name = "MATRICULE", unique = true, nullable = false, length = 30)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "NOM", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

}
