package com.model;
// Generated Apr 21, 2019 11:10:57 AM by Hibernate Tools 4.3.5.Final

import java.math.*;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pilote generated by hbm2java
 */
@Entity
@Table(name = "PILOTE")
public class Pilote implements java.io.Serializable {

	private int matP;
	private String nomP;
	private String prenomP;
	private String sexP;
	private String adrP;
	private String emailP;

	public Pilote() {
	}

	public Pilote(int matP) {
		this.matP = matP;
	}

	public Pilote(int matP, String nomP, String prenomP, String sexP, String adrP, String emailP) {
		this.matP = matP;
		this.nomP = nomP;
		this.prenomP = prenomP;
		this.sexP = sexP;
		this.adrP = adrP;
		this.emailP = emailP;
	}

	@Id

	@Column(name = "MAT_P", unique = true, nullable = false, precision = 22, scale = 0)
	public int getMatP() {
		return this.matP;
	}

	public void setMatP(int matP) {
		this.matP = matP;
	}

	@Column(name = "NOM_P", length = 50)
	public String getNomP() {
		return this.nomP;
	}

	public void setNomP(String nomP) {
		this.nomP = nomP;
	}

	@Column(name = "PRENOM_P", length = 50)
	public String getPrenomP() {
		return this.prenomP;
	}

	public void setPrenomP(String prenomP) {
		this.prenomP = prenomP;
	}

	@Column(name = "SEX_P", length = 50)
	public String getSexP() {
		return this.sexP;
	}

	public void setSexP(String sexP) {
		this.sexP = sexP;
	}

	@Column(name = "ADR_P", length = 50)
	public String getAdrP() {
		return this.adrP;
	}

	public void setAdrP(String adrP) {
		this.adrP = adrP;
	}

	@Column(name = "EMAIL_P", length = 50)
	public String getEmailP() {
		return this.emailP;
	}

	public void setEmailP(String emailP) {
		this.emailP = emailP;
	}

}
