package com.model;

// Generated 16 sept. 2018 12:54:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR")
public class Utilisateur implements java.io.Serializable {

	private UtilisateurId id;
	private String nom;
	private String prenom;

	public Utilisateur() {
	}

	public Utilisateur(UtilisateurId id, String nom, String prenom) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "loginUtilisateur", column = @Column(name = "LOGIN_UTILISATEUR", nullable = false, length = 30)),
			@AttributeOverride(name = "passwordUtilisateur", column = @Column(name = "PASSWORD_UTILISATEUR", nullable = false, length = 30)) })
	public UtilisateurId getId() {
		return this.id;
	}

	public void setId(UtilisateurId id) {
		this.id = id;
	}

	@Column(name = "NOM", nullable = false, length = 60)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 60)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

}
