package com.model;

// Generated 16 sept. 2018 12:54:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtilisateurId generated by hbm2java
 */
@Embeddable
public class UtilisateurId implements java.io.Serializable {

	private String loginUtilisateur;
	private String passwordUtilisateur;

	public UtilisateurId() {
	}

	public UtilisateurId(String loginUtilisateur, String passwordUtilisateur) {
		this.loginUtilisateur = loginUtilisateur;
		this.passwordUtilisateur = passwordUtilisateur;
	}

	@Column(name = "LOGIN_UTILISATEUR", nullable = false, length = 30)
	public String getLoginUtilisateur() {
		return this.loginUtilisateur;
	}

	public void setLoginUtilisateur(String loginUtilisateur) {
		this.loginUtilisateur = loginUtilisateur;
	}

	@Column(name = "PASSWORD_UTILISATEUR", nullable = false, length = 30)
	public String getPasswordUtilisateur() {
		return this.passwordUtilisateur;
	}

	public void setPasswordUtilisateur(String passwordUtilisateur) {
		this.passwordUtilisateur = passwordUtilisateur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtilisateurId))
			return false;
		UtilisateurId castOther = (UtilisateurId) other;

		return ((this.getLoginUtilisateur() == castOther.getLoginUtilisateur()) || (this
				.getLoginUtilisateur() != null
				&& castOther.getLoginUtilisateur() != null && this
				.getLoginUtilisateur().equals(castOther.getLoginUtilisateur())))
				&& ((this.getPasswordUtilisateur() == castOther
						.getPasswordUtilisateur()) || (this
						.getPasswordUtilisateur() != null
						&& castOther.getPasswordUtilisateur() != null && this
						.getPasswordUtilisateur().equals(
								castOther.getPasswordUtilisateur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getLoginUtilisateur() == null ? 0 : this
						.getLoginUtilisateur().hashCode());
		result = 37
				* result
				+ (getPasswordUtilisateur() == null ? 0 : this
						.getPasswordUtilisateur().hashCode());
		return result;
	}

}
